# Generated by Django 3.0.3 on 2020-02-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(auto_created=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('completed', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(auto_created=True)),
                ('description', models.CharField(max_length=500)),
                ('note', models.BooleanField()),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Projects')),
            ],
        ),
    ]
