# Generated by Django 3.0.3 on 2020-02-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200208_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='note',
            field=models.CharField(max_length=500),
        ),
    ]
